name: Shitty Coffee
favicon: null
layout_spectrum: 0.6270821287762374
typography_spectrum: 0.47318
title: Shitty Coffee Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0000'
    - '#ff9b00'
    - '#e8e8e8'
    - '#979095'
    - '#51462b'
  brandStrength: 0.7008659960702062
  lightness: 0.8460214091464877
  saturation: 0.3050917119253427
  rhythmicContrast: 0.03999774996191263
purpose: []
