name: Shitty Coffee Co.
favicon: null
layout_spectrum: 0.9731183
typography_spectrum: 0.47318
title: Shitty Coffee Co.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0000'
    - '#ff9b00'
    - '#e8e8e8'
    - '#979095'
    - '#51462b'
  brandStrength: 0.7008659960702062
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.03999774996191263
purpose: []
